server:
  port: 8080
spring:
  datasource:
    username: root
    password: C1mBCwvqpO-!
    url: jdbc:mysql://47.97.21.93:3306/qa
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: yanferr-qa
  # 配置日期类型返回格式
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8   # 24小时制

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto # 主键自增
      logic-delete-field: show_status # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

logging: #开启日志打印，能看到sql
  level:
    com.yanferr.user: debug



